### ISSUE TITLE
Error in the facebook ads connector in looker studio

### ISSUE THREAD

**Issue by Jsusglz** [Gladior-B-V/facebook-ads-connector#33] opened 2024-04-25 20:51 UTC
Hello, for a few days I have had problems viewing my dashboard in Looker Studio.

I use the Facebook ADS connector. I have tried to reconnect the Facebook ADS account and I have even tried to create another report but it could not display my data.
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/168007250/d21460b0-1a85-47fb-81df-cf30a243e91f)
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/168007250/4b9c3b5d-cc64-4e6e-82f2-6471214dfed0)

**Comment by eresfavolosx** [comment] 2024-05-03 15:33
I am also having the same issue, please advise @zoedufrenne. Thank you in advance for all the support.

**Comment by rkooiker** [comment] 2024-05-31 09:18
Hi, could you try to reconnect the credential again? If the issue persists, can you share the dashboard with service@gladior.com, and leave your Data Hub account id (this is the number shown on edit profile, should look something like: 80d7c2a3-e36b-4g98-1f35-5421ebb41edc) or email address as a comment on this issue?

**Comment by seotrackerman** [comment] 2024-06-26 22:10
Hi there, I'm having the same problem, have reconnected the data source and had to manually update each field on the report, but now it is showing in euro's even though i am using my data creditentials (should be AUD) and still the same after reconnecting the data source:
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/171210577/427616fa-bcf6-4230-9aef-38d5312a9f35)

**Comment by rkooiker** [comment] 2024-06-28 06:32
Hi @seotrackerman, could you share your Data Hub user ID? It is the grayed out number you can find when you click on your profile -> Edit profile

**Comment by seotrackerman** [comment] 2024-07-01 22:03
Hi @rkooiker no problem at all, my number is google_102919986823718903241

**Comment by rkooiker** [comment] 2024-07-03 07:02
Hello @seotrackerman, we update the account currency based on the "Account Currency" field in the connector. Can you verify that this field shows AUD? If it does you could try to create a new Data Source in looker studio, and the currency fields should be in AUD.

**Comment by seotrackerman** [comment] 2024-07-05 03:51
Hi @rkooiker it worked, however I had tried that and it wouldn't refresh the fields for me as the data source connector. but working now so happy :)

Thank you

**Comment by MikeHerbs** [comment] 2024-07-23 09:29
i am having the same issue just today

**Comment by strelokas10** [comment] 2024-07-29 10:03
![Screenshot_1](https://github.com/user-attachments/assets/ad0a87c3-6cf4-4d52-a6a9-d334d0d490e9)
![Screenshot_8](https://github.com/user-attachments/assets/0e0f111f-fb19-47c9-a162-f557fd30bcec)
Connector stopped working

**Comment by Harheeni** [comment] 2024-07-30 03:23
hi , im having connector issue for past 3 days , havent resolve yet. may i know when can solve it?
![Screenshot 2024-07-30 112233](https://github.com/user-attachments/assets/cac7231b-ce05-4133-bd95-2179218f3fba)

**Comment by rkooiker** [comment] 2024-07-30 06:06
Hi,

Have you already tried reconnecting the credential? Otherwise please leave your Data Hub account id in a comment here so I can further investigate (this is the number shown on edit profile, should look something like: 80d7c2a3-e36b-4g98-1f35-5421ebb41edc).

**Comment by Harheeni** [comment] 2024-07-30 07:02
yeah i got reconnect back from both credential and looker studio side also ya still got error. 
ID = google_117405607528998535085

**Comment by rkooiker** [comment] 2024-07-30 07:22
It appears that the requests for fetching data from facebook takes too long. This is usually an indication that you have a lot of ads. Can you verify that only retrieving a metric, such as impressions does work? Make sure you do not have a filter on Ad Id anywhere,  otherwise it will still get the metrics per ad, which takes longer.

**Comment by Harheeni** [comment] 2024-07-30 07:26
yes it is working if only  retrieving a metric , but it doesn't work when i choose for selective dates and ads ID ,also the metrics name called 'ad creative object type' always have connector issue where it didn't come out with an outcome..do u have any solution for both cases.

**Comment by rkooiker** [comment] 2024-07-30 07:32
In that case the issue is that you have more data than we can handle at the moment. Since we are a free service it is not feasible for us to process requests with too much data. You can contact us at service@gladior.com to inquire about our paid services.

**Comment by Harheeni** [comment] 2024-07-30 10:13
okies. thank you so much ya

**Comment by Harheeni** [comment] 2024-07-30 10:22
how about 'ad creative object type' ya?

**Comment by rkooiker** [comment] 2024-07-31 06:38
I believe this is caused by the same issue. ad creative object type is retrieved per ad, so even though the amount of data appears to be much simpler, it actually has to do quite a lot of work to fetch all data.

**Comment by magniandtudeacc** [comment] 2024-08-05 09:29
Hi,

I have a question about the following events. The event with the respective value is missing for all events.

Missing in general:
Add to cart value
Website purchase value

The value 0 is displayed, even though there is one:
Website Customise Products

<img width="220" alt="Bildschirmfoto 2024-08-01 um 14 33 18" src="https://github.com/user-attachments/assets/48675c71-70c2-4975-b530-e1b842440cea">
<img width="217" alt="Bildschirmfoto 2024-08-01 um 14 33 30" src="https://github.com/user-attachments/assets/fe92529b-f7ff-4a05-93ac-3d9a8b7d906a">
<img width="217" alt="Bildschirmfoto 2024-08-01 um 14 33 46" src="https://github.com/user-attachments/assets/fce47d4a-0817-422d-8b4b-a9b74aaef503">

**Comment by magniandtudeacc** [comment] 2024-08-08 08:57
@rkooiker can you help?

**Comment by strelokas10** [comment] 2024-08-14 07:18
![Screenshot_8](https://github.com/user-attachments/assets/8831587b-d72d-4460-82a8-fc2be0856783)
Good afternoon, a new conector error has come out, how do I clear it?

**Comment by rkooiker** [comment] 2024-08-14 07:35
Hi @strelokas10 , this appears to be an issue on our end, and will be fixed asap.

**Comment by rkooiker** [comment] 2024-08-14 08:27
@strelokas10 Everything should work as expected now

**Closed as completed by rkooiker** 2024-08-14 08:27 UTC

**Comment by strelokas10** [comment] 2024-08-14 09:57
Everything worked, thanks
